### ISSUE TITLE
Facing some issue when adding user/student data into database

### ISSUE THREAD

**Issue by shehper007** [vigneshshettyin/Online-Certificate-Generation-Verification#2]
Hi,
I am getting this error when adding new student information from back end...

Fatal error: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in C:\xampp\htdocs\certi\login\lib\MysqliDb\MysqliDb.php:1848 Stack trace: #0 C:\xampp\htdocs\certi\login\lib\MysqliDb\MysqliDb.php(1848): implode(Array, '`, `') #1 C:\xampp\htdocs\certi\login\lib\MysqliDb\MysqliDb.php(1572): MysqliDb->_buildInsertQuery(Array) #2 C:\xampp\htdocs\certi\login\lib\MysqliDb\MysqliDb.php(1533): MysqliDb->_buildQuery(NULL, Array) #3 C:\xampp\htdocs\certi\login\lib\MysqliDb\MysqliDb.php(820): MysqliDb->_buildInsert('customers', Array, 'INSERT') #4 C:\xampp\htdocs\certi\login\add_customer.php(17): MysqliDb->insert('customers', Array) #5 {main} thrown in C:\xampp\htdocs\certi\login\lib\MysqliDb\MysqliDb.php on line 1848

data is working perfectly if I upload from .CSV file even I can edit that after uploading but can't add manually.

**Comment by shehper007** [comment]
Brother, why did you close without even adding comment?

**Comment by vigneshshettyin** [comment]
> Brother, why did you close without even adding comment?

Hey, @shehper007 just happened by mistake I apologize for it. I haven't worked in PHP for like two years. Could you please check this on StackOverflow or any other websites ?
